### ISSUE TITLE
Blank screen when student access questionnaire

### ISSUE THREAD

**Issue by ramonovelar** [moodlepeers/moodle-mod_groupformation#46]
Hello, 
I have installed the plugin in a test environment and I have created a Group formation activity with an user with teacher role. Everything worked fine. But when I tried to access the questionnaire with an student role, I had a blank screen after press the "Next" button. I tried several times with the same result, except once, having a 500 error. 

Sometimes we have had problems when testing plugins because this test environment has not https:/ . I don't know if this can be be related with this issue. 

Moodle version is 3.1.3 (Build: 20161114)
Many thanks in advance for any help. I think this plugin can be very interesting for our university. 

Ramón Ovelar
Campus Virtual Birtuala UPV/EHU
Tel: (34) 94 601 3407 
http://ehu.es/es/web/cvb

**Comment by jkonert** [comment]
Dear Ramon,
thanks for your issue report. Which language are you using? Currently the plugin has only questionnaire translations to EN or DE. If you want to support us with more languages, the XML-files in folder ./xml_question/ need to be copied, renamed (instead of en_ then es_ etc. ) and translated.

If you use one of these two languages: It cannot be a problem with https or http. Maybe a theme problem? Are you using the clean Moodle theme or a custom one?

Looking forward to your further information. In the meantime we changed some small layout issues with the questionnaire. If you like, check out the newest code from GitHub (and don't forget to clear caches).

**Comment by rroepke** [comment]
Not reproducable, hence closed for now.
