### ISSUE TITLE
Critical Bug for Moodle 3.8: Installation of mod_groupformation causes loss of functionality in Moodle 3.8

### ISSUE THREAD

**Issue by roessling** [moodlepeers/moodle-mod_groupformation#79]
After an upgrade from Moodle 3.7.3+ (where mod_groupformation was working) to 3.8, a central part of the Moodle UI was no longer working. This especially concerned all drop-downs, so accessing/editing the profile or modifying course components was only possible if you manually called the right URL (if you knew it, that is). There were no debugging messages, but it was clear after a time-intensive administrative session (start from a clean 3.8, install one plugin, run upgrade.php, check that everything works, continue with next plugin) that mod_groupformation was in some way responsible for this. 
I could not debug what exactly inside mod_groupformation caused this behaviour, but could clearly attribute it to this plugin: _without_ mod_groupformation, our Moodle 3.8 runs flawlessly; _with_ mod_groupformation, the problems described appear for all users independent of OS or browser.

**Comment by rroepke** [comment]
First testing revealed it does happen due to our JavaScript modules and the provided builds. In debug mode where JS files are not cached it works, but this not a solution. 

It happens in the evaluation_view.php due to the startcarousel.js file and the used AMD files. Somehow the builds do not comply with the current require.js used in Moodle. First recommendation could be to rebuild our AMD files. More details about AMD can be found here: https://docs.moodle.org/dev/Javascript_Modules
It seems like there was a change from 3.7 to 3.8.

@stefanjung will take a look into it.

**Comment by mickhawkins** [comment]
Hi all,

Myself and a colleague had a look into this after @roessling detailed these issues in a [forum discussion](https://moodle.org/mod/forum/discuss.php?d=393570).

It appears that one of the issues is that the plugin is not wrapping the inclusion of 'tether' in a [_define_](https://docs.moodle.org/dev/Javascript_Modules#Minimum_.28getting_started.29_module_for_plugins) call, which is causing the function to be immediately executed on the page, causing an error. It's also worth noting that in the current version of Moodle, tether is already included as part of the Boost theme (and by extension, the Clean theme), so it would be worth checking whether you can utilise that, rather than needing to re-include it a second time.

**Comment by rroepke** [comment]
Thanks @mickhawkins - I think this will help us a lot. We need to update our JS usage definitely. @stefanjung Maybe read up on the forum discussion linked above. This define call this definitely sth we should look into.

**Comment by stefanjung** [comment]
closed. has been fixed in v.1.7
